#!/usr/bin/env python3
"""
update_changelog.py
-------------------
Aggiorna (o crea) CHANGELOG.md nel formato "Keep a Changelog" leggendo
i tag Git del repository corrente.

Regole:
- Considera solo tag semver "puri" (es. 1.2.3 oppure v1.2.3).
  Esclude prerelease: -alpha, -beta, -rc, -SNAPSHOT, ecc.
- Se CHANGELOG.md non esiste, lo crea a partire dal primo tag.
- Se esiste, rileva quali tag mancano e li inserisce nell'ordine giusto
  (versioni piu' recenti in cima).
- Mantiene una sezione [Unreleased] con i commit successivi all'ultimo tag.
- Include TUTTI i commit (nessun filtro) sotto un'unica sezione "Changed".
- Converte gitmoji shortcode (":sparkles:") nel loro equivalente unicode ("✨")
  cosi' da renderizzare correttamente nel markdown.

Uso:
    python scripts/update_changelog.py            # aggiorna il file
    python scripts/update_changelog.py --check    # exit 1 se mancano tag
    python scripts/update_changelog.py --dry-run  # stampa senza scrivere
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path


# ---------------------------------------------------------------------------
# Costanti
# ---------------------------------------------------------------------------

CHANGELOG_FILENAME = "CHANGELOG.md"

# Semver "stabile": accetta "1.2.3" o "v1.2.3". Nessun suffisso (-alpha, -rc, ...).
SEMVER_STABLE_RE = re.compile(r"^v?(\d+)\.(\d+)\.(\d+)$")

# Header di versione nel changelog: "## [1.2.3] - 2024-01-15" oppure "## 1.2.3"
# Cattura la versione per capire quali tag sono gia' documentati.
CHANGELOG_VERSION_HEADER_RE = re.compile(
    r"^##\s+\[?(v?\d+\.\d+\.\d+)\]?",
    re.MULTILINE,
)

CHANGELOG_HEADER = """# Changelog

<!-- This file is autogenerated by scripts/update_changelog.py. DO NOT EDIT MANUALLY. -->
<!-- Last generated: {timestamp} -->

> **Note**: This file is automatically generated from git tags and commit messages.
> Any manual edits will be overwritten on the next run of the update script.

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.1.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

"""

# Regex per trovare e aggiornare la riga "Last generated: ..." ad ogni esecuzione.
LAST_GENERATED_RE = re.compile(
    r"<!--\s*Last generated:.*?-->",
    re.DOTALL,
)


def current_timestamp_utc() -> str:
    """Ritorna il timestamp UTC corrente nel formato 'YYYY-MM-DD HH:MM:SS UTC'."""
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")


# ---------------------------------------------------------------------------
# Data model
# ---------------------------------------------------------------------------

@dataclass
class Version:
    """Rappresenta una versione semver stabile."""
    raw: str            # come appare nel tag git, es. "v1.2.3"
    major: int
    minor: int
    patch: int

    @property
    def clean(self) -> str:
        """Versione senza prefisso 'v', per l'header del changelog."""
        return f"{self.major}.{self.minor}.{self.patch}"

    def sort_key(self) -> tuple[int, int, int]:
        return (self.major, self.minor, self.patch)

    @classmethod
    def parse(cls, tag: str) -> "Version | None":
        m = SEMVER_STABLE_RE.match(tag.strip())
        if not m:
            return None
        return cls(raw=tag, major=int(m.group(1)),
                   minor=int(m.group(2)), patch=int(m.group(3)))


@dataclass
class Release:
    """Una release da scrivere nel changelog."""
    version: Version
    date: str                                      # YYYY-MM-DD
    entries: list[str] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Git helpers
# ---------------------------------------------------------------------------

def run_git(*args: str) -> str:
    """Esegue git e ritorna stdout. Solleva RuntimeError in caso di errore."""
    result = subprocess.run(
        ["git", *args],
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        raise RuntimeError(
            f"git {' '.join(args)} fallito: {result.stderr.strip()}"
        )
    return result.stdout


def repo_root() -> Path:
    out = run_git("rev-parse", "--show-toplevel").strip()
    return Path(out)


def list_stable_tags() -> list[Version]:
    """Ritorna tutti i tag semver stabili, dal piu' recente al piu' vecchio."""
    raw = run_git("tag", "--list").splitlines()
    versions = [v for v in (Version.parse(t) for t in raw) if v is not None]
    versions.sort(key=Version.sort_key, reverse=True)
    return versions


def tag_date(tag: str) -> str:
    """Data (YYYY-MM-DD) del commit puntato dal tag."""
    out = run_git("log", "-1", "--format=%ad", "--date=short", tag).strip()
    return out


def commits_between(from_ref: str | None, to_ref: str) -> list[str]:
    """Lista di commit subject tra due ref (from escluso, to incluso).

    Se from_ref e' None, prende tutta la storia fino a to_ref.
    """
    rev_range = f"{from_ref}..{to_ref}" if from_ref else to_ref
    out = run_git("log", rev_range, "--pretty=format:%s", "--no-merges")
    return [line for line in out.splitlines() if line.strip()]


def has_commits_after(ref: str) -> bool:
    """True se ci sono commit dopo il ref indicato (fino a HEAD)."""
    out = run_git("log", f"{ref}..HEAD", "--pretty=format:%H").strip()
    return bool(out)


# ---------------------------------------------------------------------------
# Normalizzazione commit: converte gitmoji shortcode in unicode
# ---------------------------------------------------------------------------
# Tutti i commit vengono messi sotto "Changed" senza filtri ne' categorizzazione.
# L'unica trasformazione e' convertire ":sparkles:" in "✨" ecc. per evitare
# che gli shortcode restino non renderizzati nel markdown.
#
# Fonte: https://gitmoji.dev - lista completa delle gitmoji ufficiali.

GITMOJI_SHORTCODE_TO_UNICODE: dict[str, str] = {
    "art": "🎨",
    "zap": "⚡️",
    "fire": "🔥",
    "bug": "🐛",
    "ambulance": "🚑️",
    "sparkles": "✨",
    "memo": "📝",
    "rocket": "🚀",
    "lipstick": "💄",
    "tada": "🎉",
    "white_check_mark": "✅",
    "lock": "🔒️",
    "closed_lock_with_key": "🔐",
    "bookmark": "🔖",
    "rotating_light": "🚨",
    "construction": "🚧",
    "green_heart": "💚",
    "arrow_down": "⬇️",
    "arrow_up": "⬆️",
    "pushpin": "📌",
    "construction_worker": "👷",
    "chart_with_upwards_trend": "📈",
    "recycle": "♻️",
    "heavy_plus_sign": "➕",
    "heavy_minus_sign": "➖",
    "wrench": "🔧",
    "hammer": "🔨",
    "globe_with_meridians": "🌐",
    "pencil2": "✏️",
    "poop": "💩",
    "rewind": "⏪️",
    "twisted_rightwards_arrows": "🔀",
    "package": "📦️",
    "alien": "👽️",
    "truck": "🚚",
    "page_facing_up": "📄",
    "boom": "💥",
    "bento": "🍱",
    "wheelchair": "♿️",
    "bulb": "💡",
    "beers": "🍻",
    "speech_balloon": "💬",
    "card_file_box": "🗃️",
    "loud_sound": "🔊",
    "mute": "🔇",
    "busts_in_silhouette": "👥",
    "children_crossing": "🚸",
    "building_construction": "🏗️",
    "iphone": "📱",
    "clown_face": "🤡",
    "egg": "🥚",
    "see_no_evil": "🙈",
    "camera_flash": "📸",
    "alembic": "⚗️",
    "mag": "🔍️",
    "label": "🏷️",
    "seedling": "🌱",
    "triangular_flag_on_post": "🚩",
    "goal_net": "🥅",
    "dizzy": "💫",
    "wastebasket": "🗑️",
    "passport_control": "🛂",
    "adhesive_bandage": "🩹",
    "monocle_face": "🧐",
    "coffin": "⚰️",
    "test_tube": "🧪",
    "necktie": "👔",
    "stethoscope": "🩺",
    "bricks": "🧱",
    "technologist": "🧑‍💻",
    "money_with_wings": "💸",
    "thread": "🧵",
    "safety_vest": "🦺",
    "airplane": "✈️",
}

# Regex per shortcode in qualunque posizione del messaggio
_SHORTCODE_RE = re.compile(r":([a-z0-9_+\-]+):")


def normalize_commit(subject: str) -> str | None:
    """Pulisce un subject di commit per il changelog.

    - Converte gitmoji shortcode (:sparkles:) nel loro unicode corrispondente.
    - Non categorizza, non filtra, non modifica altro.
    - Ritorna None se il subject e' vuoto.
    """
    subject = subject.strip()
    if not subject:
        return None

    def _replace(match: re.Match) -> str:
        token = match.group(1)
        unicode_char = GITMOJI_SHORTCODE_TO_UNICODE.get(token)
        if unicode_char is not None:
            return unicode_char
        # Shortcode sconosciuto: lo lascio intatto (potrebbe essere
        # un riferimento legittimo come ":hh:mm:" o simili)
        return match.group(0)

    return _SHORTCODE_RE.sub(_replace, subject).strip()


def build_entries(commits: list[str]) -> list[str]:
    """Ritorna la lista di commit normalizzati, deduplicata, per la sezione Changed."""
    items: list[str] = []
    seen: set[str] = set()
    for subject in commits:
        normalized = normalize_commit(subject)
        if not normalized:
            continue
        key = normalized.lower()
        if key in seen:
            continue
        seen.add(key)
        items.append(normalized)
    return items


# ---------------------------------------------------------------------------
# Parsing / rendering del CHANGELOG
# ---------------------------------------------------------------------------

def parse_existing_versions(changelog_path: Path) -> set[str]:
    """Ritorna l'insieme delle versioni gia' documentate (formato pulito, senza 'v')."""
    if not changelog_path.exists():
        return set()
    text = changelog_path.read_text(encoding="utf-8")
    versions: set[str] = set()
    for m in CHANGELOG_VERSION_HEADER_RE.finditer(text):
        v = m.group(1).lstrip("v")
        versions.add(v)
    return versions


def render_release(release: Release) -> str:
    """Renderizza una release nel formato Keep a Changelog (sezione unica Changed)."""
    lines = [f"## [{release.version.clean}] - {release.date}", ""]
    if release.entries:
        lines.append("### Changed")
        lines.extend(f"- {item}" for item in release.entries)
        lines.append("")
    return "\n".join(lines) + "\n"


def render_unreleased(entries: list[str]) -> str:
    lines = ["## [Unreleased]", ""]
    if not entries:
        lines.append("_Nothing yet._")
        lines.append("")
        return "\n".join(lines) + "\n"
    lines.append("### Changed")
    lines.extend(f"- {item}" for item in entries)
    lines.append("")
    return "\n".join(lines) + "\n"


def strip_unreleased_section(body: str) -> str:
    """Rimuove l'eventuale sezione [Unreleased] esistente dal corpo del changelog."""
    pattern = re.compile(
        r"##\s+\[Unreleased\].*?(?=^##\s+\[?v?\d+\.\d+\.\d+\]?|\Z)",
        re.DOTALL | re.MULTILINE,
    )
    return pattern.sub("", body, count=1).lstrip("\n")


# ---------------------------------------------------------------------------
# Logica principale
# ---------------------------------------------------------------------------

def build_missing_releases(
    all_versions: list[Version],
    known_versions: set[str],
) -> list[Release]:
    """Calcola le Release da aggiungere al changelog."""
    # all_versions e' ordinato dal piu' recente al piu' vecchio.
    # Per costruire i range abbiamo bisogno dell'ordine cronologico.
    chronological = list(reversed(all_versions))

    missing: list[Release] = []
    prev_tag_raw: str | None = None
    for v in chronological:
        if v.clean not in known_versions:
            commits = commits_between(prev_tag_raw, v.raw)
            entries = build_entries(commits)
            release = Release(version=v, date=tag_date(v.raw), entries=entries)
            missing.append(release)
        prev_tag_raw = v.raw

    # Riordina dalla piu' recente alla piu' vecchia per la scrittura
    missing.sort(key=lambda r: r.version.sort_key(), reverse=True)
    return missing


def build_unreleased_entries(all_versions: list[Version]) -> list[str]:
    if not all_versions:
        commits = commits_between(None, "HEAD")
    else:
        latest = all_versions[0].raw
        if not has_commits_after(latest):
            return []
        commits = commits_between(latest, "HEAD")
    return build_entries(commits)


def write_changelog(
    changelog_path: Path,
    new_releases: list[Release],
    unreleased: list[str],
) -> str:
    """Scrive il changelog unendo contenuto esistente e nuove sezioni. Ritorna il testo finale."""
    timestamp = current_timestamp_utc()

    if changelog_path.exists():
        existing = changelog_path.read_text(encoding="utf-8")
        # Separa header (tutto fino al primo ## [versione] o [Unreleased]) dal body
        split_re = re.compile(
            r"^##\s+\[?(?:Unreleased|v?\d+\.\d+\.\d+)\]?",
            re.MULTILINE,
        )
        m = split_re.search(existing)
        if m:
            header = existing[:m.start()]
            body = existing[m.start():]
        else:
            header = existing if existing.endswith("\n") else existing + "\n"
            body = ""
        body = strip_unreleased_section(body)

        # Aggiorna il timestamp nell'header esistente.
        # Se manca (header legacy da versioni precedenti), rigenera l'header
        # completo cosi' anche file vecchi si normalizzano al formato nuovo.
        new_last_gen = f"<!-- Last generated: {timestamp} -->"
        if LAST_GENERATED_RE.search(header):
            header = LAST_GENERATED_RE.sub(new_last_gen, header)
        else:
            header = CHANGELOG_HEADER.format(timestamp=timestamp)
    else:
        header = CHANGELOG_HEADER.format(timestamp=timestamp)
        body = ""

    new_sections = render_unreleased(unreleased)
    for release in new_releases:
        new_sections += render_release(release)

    final = header.rstrip() + "\n\n" + new_sections + body.lstrip()
    # Normalizza: max una riga vuota consecutiva
    final = re.sub(r"\n{3,}", "\n\n", final)
    if not final.endswith("\n"):
        final += "\n"

    changelog_path.write_text(final, encoding="utf-8")
    return final


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Aggiorna CHANGELOG.md dai tag git.")
    parser.add_argument("--check", action="store_true",
                        help="Exit 1 se ci sono tag non documentati. Non scrive il file.")
    parser.add_argument("--dry-run", action="store_true",
                        help="Stampa cosa verrebbe scritto senza modificare il file.")
    parser.add_argument("--path", type=Path, default=None,
                        help="Percorso del CHANGELOG.md (default: <repo_root>/CHANGELOG.md).")
    args = parser.parse_args(argv)

    try:
        root = repo_root()
    except RuntimeError as e:
        print(f"Errore: non sembra un repository git ({e})", file=sys.stderr)
        return 2

    changelog_path = args.path or (root / CHANGELOG_FILENAME)

    all_versions = list_stable_tags()
    if not all_versions:
        print("Nessun tag semver stabile trovato. Niente da fare.")
        return 0

    known = parse_existing_versions(changelog_path)
    missing = build_missing_releases(all_versions, known)
    unreleased = build_unreleased_entries(all_versions)

    if args.check:
        if missing:
            print(f"Tag non documentati nel changelog: "
                  f"{', '.join(r.version.clean for r in missing)}")
            return 1
        print("Changelog allineato con i tag git.")
        return 0

    if not missing and not unreleased:
        print("Changelog gia' aggiornato. Nessuna modifica necessaria.")
        return 0

    if args.dry_run:
        print("=== DRY RUN ===")
        if missing:
            print(f"Aggiungerei {len(missing)} release: "
                  f"{', '.join(r.version.clean for r in missing)}")
        if unreleased:
            print(f"Sezione [Unreleased]: {len(unreleased)} commit")
        return 0

    write_changelog(changelog_path, missing, unreleased)
    if missing:
        print(f"CHANGELOG.md aggiornato con {len(missing)} nuova/e release: "
              f"{', '.join(r.version.clean for r in missing)}")
    else:
        print("CHANGELOG.md aggiornato (sezione [Unreleased]).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
