#!/usr/bin/env python3
"""
update_changelog.py
-------------------
Updates (or creates) CHANGELOG.md in the "Keep a Changelog" format by reading
the Git tags of the current repository.

Rules:
- Only considers "pure" semver tags (e.g. 1.2.3 or v1.2.3).
  Excludes prereleases: -alpha, -beta, -rc, -SNAPSHOT, etc.
- If CHANGELOG.md does not exist, it is created starting from the first tag.
- If it exists, detects which tags are missing and inserts them in the right
  order (most recent versions on top).
- Keeps an [Unreleased] section with the commits after the latest tag.
- Includes ALL commits (no filtering) under a single "Changed" section.
- Converts gitmoji shortcodes (":sparkles:") into their unicode equivalent ("✨")
  so they render correctly in markdown.

Usage:
    python scripts/update_changelog.py            # update the file
    python scripts/update_changelog.py --check    # exit 1 if tags are missing
    python scripts/update_changelog.py --dry-run  # print without writing
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

CHANGELOG_FILENAME = "CHANGELOG.md"

# "Stable" semver: accepts "1.2.3" or "v1.2.3". No suffix (-alpha, -rc, ...).
SEMVER_STABLE_RE = re.compile(r"^v?(\d+)\.(\d+)\.(\d+)$")

# Version header in the changelog: "## [1.2.3] - 2024-01-15" or "## 1.2.3".
# Captures the version to figure out which tags are already documented.
CHANGELOG_VERSION_HEADER_RE = re.compile(
    r"^##\s+\[?(v?\d+\.\d+\.\d+)\]?",
    re.MULTILINE,
)

CHANGELOG_HEADER = """# Changelog

<!-- This file is autogenerated by scripts/update_changelog.py. DO NOT EDIT MANUALLY. -->
<!-- Last generated: {timestamp} -->

> **Note**: This file is automatically generated from git tags and commit messages.
> Any manual edits will be overwritten on the next run of the update script.

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.1.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

"""

# Regex to find and update the "Last generated: ..." line on every run.
LAST_GENERATED_RE = re.compile(
    r"<!--\s*Last generated:.*?-->",
    re.DOTALL,
)


def current_timestamp_utc() -> str:
    """Returns the current UTC timestamp in 'YYYY-MM-DD HH:MM:SS UTC' format."""
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")


# ---------------------------------------------------------------------------
# Data model
# ---------------------------------------------------------------------------

@dataclass
class Version:
    """Represents a stable semver version."""
    raw: str            # as it appears in the git tag, e.g. "v1.2.3"
    major: int
    minor: int
    patch: int

    @property
    def clean(self) -> str:
        """Version without the 'v' prefix, for the changelog header."""
        return f"{self.major}.{self.minor}.{self.patch}"

    def sort_key(self) -> tuple[int, int, int]:
        return (self.major, self.minor, self.patch)

    @classmethod
    def parse(cls, tag: str) -> "Version | None":
        m = SEMVER_STABLE_RE.match(tag.strip())
        if not m:
            return None
        return cls(raw=tag, major=int(m.group(1)),
                   minor=int(m.group(2)), patch=int(m.group(3)))


@dataclass
class Release:
    """A release to write into the changelog."""
    version: Version
    date: str                                      # YYYY-MM-DD
    entries: list[str] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Git helpers
# ---------------------------------------------------------------------------

def run_git(*args: str) -> str:
    """Runs git and returns stdout. Raises RuntimeError on failure."""
    result = subprocess.run(
        ["git", *args],
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        raise RuntimeError(
            f"git {' '.join(args)} failed: {result.stderr.strip()}"
        )
    return result.stdout


def repo_root() -> Path:
    out = run_git("rev-parse", "--show-toplevel").strip()
    return Path(out)


def list_stable_tags() -> list[Version]:
    """Returns all stable semver tags, from most recent to oldest."""
    raw = run_git("tag", "--list").splitlines()
    versions = [v for v in (Version.parse(t) for t in raw) if v is not None]
    versions.sort(key=Version.sort_key, reverse=True)
    return versions


def tag_date(tag: str) -> str:
    """Date (YYYY-MM-DD) of the commit the tag points to."""
    out = run_git("log", "-1", "--format=%ad", "--date=short", tag).strip()
    return out


def commits_between(from_ref: str | None, to_ref: str) -> list[str]:
    """List of commit subjects between two refs (from excluded, to included).

    If from_ref is None, takes the whole history up to to_ref.
    """
    rev_range = f"{from_ref}..{to_ref}" if from_ref else to_ref
    out = run_git("log", rev_range, "--pretty=format:%s", "--no-merges")
    return [line for line in out.splitlines() if line.strip()]


def has_commits_after(ref: str) -> bool:
    """True if there are commits after the given ref (up to HEAD)."""
    out = run_git("log", f"{ref}..HEAD", "--pretty=format:%H").strip()
    return bool(out)


# ---------------------------------------------------------------------------
# Commit normalization: convert gitmoji shortcodes to unicode
# ---------------------------------------------------------------------------
# All commits go under "Changed" without filtering or categorization.
# The only transformation is converting ":sparkles:" into "✨" etc. to avoid
# leaving shortcodes unrendered in the markdown.
#
# Source: https://gitmoji.dev - complete list of the official gitmoji.

GITMOJI_SHORTCODE_TO_UNICODE: dict[str, str] = {
    "art": "🎨",
    "zap": "⚡️",
    "fire": "🔥",
    "bug": "🐛",
    "ambulance": "🚑️",
    "sparkles": "✨",
    "memo": "📝",
    "rocket": "🚀",
    "lipstick": "💄",
    "tada": "🎉",
    "white_check_mark": "✅",
    "lock": "🔒️",
    "closed_lock_with_key": "🔐",
    "bookmark": "🔖",
    "rotating_light": "🚨",
    "construction": "🚧",
    "green_heart": "💚",
    "arrow_down": "⬇️",
    "arrow_up": "⬆️",
    "pushpin": "📌",
    "construction_worker": "👷",
    "chart_with_upwards_trend": "📈",
    "recycle": "♻️",
    "heavy_plus_sign": "➕",
    "heavy_minus_sign": "➖",
    "wrench": "🔧",
    "hammer": "🔨",
    "globe_with_meridians": "🌐",
    "pencil2": "✏️",
    "poop": "💩",
    "rewind": "⏪️",
    "twisted_rightwards_arrows": "🔀",
    "package": "📦️",
    "alien": "👽️",
    "truck": "🚚",
    "page_facing_up": "📄",
    "boom": "💥",
    "bento": "🍱",
    "wheelchair": "♿️",
    "bulb": "💡",
    "beers": "🍻",
    "speech_balloon": "💬",
    "card_file_box": "🗃️",
    "loud_sound": "🔊",
    "mute": "🔇",
    "busts_in_silhouette": "👥",
    "children_crossing": "🚸",
    "building_construction": "🏗️",
    "iphone": "📱",
    "clown_face": "🤡",
    "egg": "🥚",
    "see_no_evil": "🙈",
    "camera_flash": "📸",
    "alembic": "⚗️",
    "mag": "🔍️",
    "label": "🏷️",
    "seedling": "🌱",
    "triangular_flag_on_post": "🚩",
    "goal_net": "🥅",
    "dizzy": "💫",
    "wastebasket": "🗑️",
    "passport_control": "🛂",
    "adhesive_bandage": "🩹",
    "monocle_face": "🧐",
    "coffin": "⚰️",
    "test_tube": "🧪",
    "necktie": "👔",
    "stethoscope": "🩺",
    "bricks": "🧱",
    "technologist": "🧑‍💻",
    "money_with_wings": "💸",
    "thread": "🧵",
    "safety_vest": "🦺",
    "airplane": "✈️",
}

# Regex for a shortcode anywhere in the message
_SHORTCODE_RE = re.compile(r":([a-z0-9_+\-]+):")


def normalize_commit(subject: str) -> str | None:
    """Cleans a commit subject for the changelog.

    - Converts gitmoji shortcodes (:sparkles:) into their unicode equivalent.
    - Does not categorize, filter, or change anything else.
    - Returns None if the subject is empty.
    """
    subject = subject.strip()
    if not subject:
        return None

    def _replace(match: re.Match) -> str:
        token = match.group(1)
        unicode_char = GITMOJI_SHORTCODE_TO_UNICODE.get(token)
        if unicode_char is not None:
            return unicode_char
        # Unknown shortcode: leave it untouched (it might be a legitimate
        # reference such as ":hh:mm:" or similar)
        return match.group(0)

    return _SHORTCODE_RE.sub(_replace, subject).strip()


def build_entries(commits: list[str]) -> list[str]:
    """Returns the list of normalized, deduplicated commits for the Changed section."""
    items: list[str] = []
    seen: set[str] = set()
    for subject in commits:
        normalized = normalize_commit(subject)
        if not normalized:
            continue
        key = normalized.lower()
        if key in seen:
            continue
        seen.add(key)
        items.append(normalized)
    return items


# ---------------------------------------------------------------------------
# Parsing / rendering of the CHANGELOG
# ---------------------------------------------------------------------------

def parse_existing_versions(changelog_path: Path) -> set[str]:
    """Returns the set of already-documented versions (clean format, without 'v')."""
    if not changelog_path.exists():
        return set()
    text = changelog_path.read_text(encoding="utf-8")
    versions: set[str] = set()
    for m in CHANGELOG_VERSION_HEADER_RE.finditer(text):
        v = m.group(1).lstrip("v")
        versions.add(v)
    return versions


def render_release(release: Release) -> str:
    """Renders a release in the Keep a Changelog format (single Changed section)."""
    lines = [f"## [{release.version.clean}] - {release.date}", ""]
    if release.entries:
        lines.append("### Changed")
        lines.extend(f"- {item}" for item in release.entries)
        lines.append("")
    return "\n".join(lines) + "\n"


def render_unreleased(entries: list[str]) -> str:
    lines = ["## [Unreleased]", ""]
    if not entries:
        lines.append("_Nothing yet._")
        lines.append("")
        return "\n".join(lines) + "\n"
    lines.append("### Changed")
    lines.extend(f"- {item}" for item in entries)
    lines.append("")
    return "\n".join(lines) + "\n"


def strip_unreleased_section(body: str) -> str:
    """Removes the existing [Unreleased] section (if any) from the changelog body."""
    pattern = re.compile(
        r"##\s+\[Unreleased\].*?(?=^##\s+\[?v?\d+\.\d+\.\d+\]?|\Z)",
        re.DOTALL | re.MULTILINE,
    )
    return pattern.sub("", body, count=1).lstrip("\n")


# ---------------------------------------------------------------------------
# Main logic
# ---------------------------------------------------------------------------

def build_missing_releases(
    all_versions: list[Version],
    known_versions: set[str],
) -> list[Release]:
    """Computes the Releases to add to the changelog."""
    # all_versions is ordered from most recent to oldest.
    # To build the ranges we need chronological order.
    chronological = list(reversed(all_versions))

    missing: list[Release] = []
    prev_tag_raw: str | None = None
    for v in chronological:
        if v.clean not in known_versions:
            commits = commits_between(prev_tag_raw, v.raw)
            entries = build_entries(commits)
            release = Release(version=v, date=tag_date(v.raw), entries=entries)
            missing.append(release)
        prev_tag_raw = v.raw

    # Reorder from most recent to oldest for writing
    missing.sort(key=lambda r: r.version.sort_key(), reverse=True)
    return missing


def build_unreleased_entries(all_versions: list[Version]) -> list[str]:
    if not all_versions:
        commits = commits_between(None, "HEAD")
    else:
        latest = all_versions[0].raw
        if not has_commits_after(latest):
            return []
        commits = commits_between(latest, "HEAD")
    return build_entries(commits)


def write_changelog(
    changelog_path: Path,
    new_releases: list[Release],
    unreleased: list[str],
) -> str:
    """Writes the changelog merging existing content and new sections. Returns the final text."""
    timestamp = current_timestamp_utc()

    if changelog_path.exists():
        existing = changelog_path.read_text(encoding="utf-8")
        # Split the header (everything up to the first ## [version] or [Unreleased]) from the body
        split_re = re.compile(
            r"^##\s+\[?(?:Unreleased|v?\d+\.\d+\.\d+)\]?",
            re.MULTILINE,
        )
        m = split_re.search(existing)
        if m:
            header = existing[:m.start()]
            body = existing[m.start():]
        else:
            header = existing if existing.endswith("\n") else existing + "\n"
            body = ""
        body = strip_unreleased_section(body)

        # Update the timestamp in the existing header.
        # If it is missing (legacy header from older versions), regenerate the
        # full header so old files normalize to the new format too.
        new_last_gen = f"<!-- Last generated: {timestamp} -->"
        if LAST_GENERATED_RE.search(header):
            header = LAST_GENERATED_RE.sub(new_last_gen, header)
        else:
            header = CHANGELOG_HEADER.format(timestamp=timestamp)
    else:
        header = CHANGELOG_HEADER.format(timestamp=timestamp)
        body = ""

    new_sections = render_unreleased(unreleased)
    for release in new_releases:
        new_sections += render_release(release)

    final = header.rstrip() + "\n\n" + new_sections + body.lstrip()
    # Normalize: at most one consecutive blank line
    final = re.sub(r"\n{3,}", "\n\n", final)
    if not final.endswith("\n"):
        final += "\n"

    # Avoid spurious rewrites: if the only difference from the existing file is
    # the "Last generated" line, leave the file (and its timestamp) untouched.
    # This keeps `git diff` clean across runs with no real changes.
    if changelog_path.exists():
        old = changelog_path.read_text(encoding="utf-8")
        if LAST_GENERATED_RE.sub("", old) == LAST_GENERATED_RE.sub("", final):
            return old

    changelog_path.write_text(final, encoding="utf-8")
    return final


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Update CHANGELOG.md from git tags.")
    parser.add_argument("--check", action="store_true",
                        help="Exit 1 if there are undocumented tags. Does not write the file.")
    parser.add_argument("--dry-run", action="store_true",
                        help="Print what would be written without modifying the file.")
    parser.add_argument("--path", type=Path, default=None,
                        help="Path to CHANGELOG.md (default: <repo_root>/CHANGELOG.md).")
    args = parser.parse_args(argv)

    try:
        root = repo_root()
    except RuntimeError as e:
        print(f"Error: this does not look like a git repository ({e})", file=sys.stderr)
        return 2

    changelog_path = args.path or (root / CHANGELOG_FILENAME)

    all_versions = list_stable_tags()
    if not all_versions:
        print("No stable semver tag found. Nothing to do.")
        return 0

    known = parse_existing_versions(changelog_path)
    missing = build_missing_releases(all_versions, known)
    unreleased = build_unreleased_entries(all_versions)

    if args.check:
        if missing:
            print(f"Tags not documented in the changelog: "
                  f"{', '.join(r.version.clean for r in missing)}")
            return 1
        print("Changelog is in sync with the git tags.")
        return 0

    if not missing and not unreleased:
        print("Changelog already up to date. No changes needed.")
        return 0

    if args.dry_run:
        print("=== DRY RUN ===")
        if missing:
            print(f"Would add {len(missing)} release(s): "
                  f"{', '.join(r.version.clean for r in missing)}")
        if unreleased:
            print(f"[Unreleased] section: {len(unreleased)} commit(s)")
        return 0

    before = changelog_path.read_text(encoding="utf-8") if changelog_path.exists() else None
    after = write_changelog(changelog_path, missing, unreleased)

    if before == after:
        print("Changelog already up to date. No changes needed.")
    elif missing:
        print(f"CHANGELOG.md updated with {len(missing)} new release(s): "
              f"{', '.join(r.version.clean for r in missing)}")
    else:
        print("CHANGELOG.md updated ([Unreleased] section).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
